services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: semonitor
      TZ: 'UTC'
      PGTZ: 'UTC'
    ports:
      - 5444:5432
    container_name: sem_tsdb
